### ISSUE TITLE
Compiling issue with Angular in Ivy full compilation mode

### ISSUE THREAD

**Issue by Way** [celsomtrindade/ngx-modalview#1]
Compiling the library I'm getting the following error:

```
Compiling with Angular sources in Ivy full compilation mode.
../../../node_modules/ngx-modalview/ngx-modal/ngx-modal-draggable.directive.d.ts:40:92 - error TS2344: Type '{ dragHandle: { alias: "dragHandle"; required: false; }; dragTarget: { alias: "dragTarget"; required: false; }; dragEnabled: { alias: "dragEnabled"; required: false; }; dialogDragOffset: { alias: "dialogDragOffset"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"dragHandle"' is incompatible with index signature.
    Type '{ alias: "dragHandle"; required: false; }' is not assignable to type 'string'.
```

**Comment by celsomtrindade** [comment]
@Way  I just released a new version with some fixes. Can you try again, please?

You were using the project without it being ready yet 😄

---

Just as a note, I'm using it in a couple of projects using Angular v16 and it's working just fine.

**Comment by jobeljohny** [comment]
I too am actually getting the same error. I just tried it out today

**Comment by celsomtrindade** [comment]
@jobeljohny I'm a bit busy to test and fix it. Do you mind creating a PR?

**Comment by Way** [comment]
There is no longer a problem on my part, the lib in Angular 16 works without any problems for me.
As far as I'm concerned, the issue can be closed.
